### ISSUE TITLE
ADD sonar.gradle.skipCompile usage to Gradle examples

### ISSUE THREAD

**Issue by G00fY2** [SonarSource/sonar-scanning-examples#169]
As the titles states, the examples should not cause deprecation warning logs.

Therefore these changes should be adapted:
https://sonarsource.atlassian.net/browse/SONARGRADL-130
https://sonarsource.atlassian.net/browse/SONARGRADL-132

**Comment by trajano** [comment]
What I did was add it to `settings.gradle`
```
rootProject.name = 'my-ms'
System.setProperty("sonar.gradle.skipCompile", "true")
```

**Comment by joe-tingsanchali-sonarsource** [comment]
Hello @G00fY2 , thank you for raising the issue in our Sonar Community [here](https://community.sonarsource.com/t/sonar-gradle-skipcompile-is-not-working/102710).

@G00fY2, @trajano : please note that setting it in `settings.gradle` is not expected. This is a bug that we will address: https://sonarsource.atlassian.net/browse/SONARGRADL-134

Eventually, `sonar.gadle.skipCompile` will disappear since we will eventually set this parameter as `true` by default.

**Comment by joe-tingsanchali-sonarsource** [comment]
Closing this issue. Please see [SONARGRADL-134](https://sonarsource.atlassian.net/browse/SONARGRADL-134) for further status on fixing this issue.
