### ISSUE TITLE
New coverage path for coverage data with Xcode 10

### ISSUE THREAD

**Issue by ladislas** [SonarSource/sonar-scanning-examples#34]
The output path of Xcode coverage tool has changed.

Xcode9 : `DerivedData/{build}/Logs/Test/{testpass}.xcovreport`
Xcode10 : `DerivedData/{build}/Logs/Test/{testpass}.xcresult/{#}_Test/action.xcovreport`

as reported here: https://github.com/nakiostudio/xcov/issues/135

**Comment by UMUTBAYGUT** [comment]
How we get testpass and {#} values in the Jenkins command line ?

**Comment by ladislas** [comment]
@UMUTBAYGUT I first build the project like this:

```shell
xcodebuild -project $PROJECT -scheme $SCHEME -derivedDataPath $DERIVED_DATA -enableCodeCoverage YES clean build test CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO"
```

You need to provide the `$PROJECT`, `$SHEME` and `$DERIVED_DATA` that work for you.

Then the archive path will be:

```shell
$DERIVED_DATA/Logs/Test/*.xcresult/*_Test/action.xccovarchive/
```

**Comment by ladislas** [comment]
@schayes04 @UMUTBAYGUT @davidwellsmith

I've set up an example repo using for Travis CI & SonarCloud integration, if it can be useful.

**Comment by UMUTBAYGUT** [comment]
I am using this file for generic  sonarqube file. Bu it takes a long long long time. . about 5 hours....

**Comment by ladislas** [comment]
I'm not using sonarqube so I can't help you, I just use the online tools.
My project are quite small (modules mostly) so it's pretty quick. I guess that if your project is huge it can take quite some time.

**Comment by davidwellsmith** [comment]
@UMUTBAYGUT check that you are only inputting the xccovarchive. It should only take about a minute to process thousands of lines of code coverage reports.

**Comment by davidwellsmith** [comment]
@UMUTBAYGUT `xccovarchive` is the file generated after running your tests so your invocation of the script should look something like:

`xccov-to-sonarqube-generic.sh /Users/xxxxx/Library/Developer/Xcode/DerivedData/xxxxx/Logs/Test/*.xcresult/*_Test/action.xccovarchive/`

**Comment by UMUTBAYGUT** [comment]
thanks david , its run but I cant see code coverage in the sonarqube

**Comment by stonedauwg** [comment]
Will sonar team be fixing this in the read me with tips on how to find the new path?

**Comment by guillermomartinez-accenture** [comment]
Same here, I've been able to generate the SonarQube file, but in Sonar it shows 0.0% coverage.

**Comment by kacpermazurkiewicz** [comment]
I was trying to test the script with the above Xcode10 path after compiling the example code with the Xcode 11-beta
`$DERIVED_DATA/Logs/Test/*.xcresult/*_Test/action.xccovarchive/`

Unfortunately, it returns an error like below
`Error: Error Domain=XCCovErrorDomain Code=0 "Failed to create unarchiver" UserInfo={NSLocalizedDescription=Failed to create unarchiver, NSUnderlyingError=0x7fe0b7c1ecd0 {Error Domain=NSCocoaErrorDomain Code=260 "The file “Metadata.plist” couldn’t be opened because there is no such file." UserInfo={NSFilePath=/Users/username/Downloads/sonar-scanning-examples-master/swift-coverage/swift-coverage-example/Build/Logs/Test/*.xcresult/*_Test/*.xccovarchive/Metadata.plist, NSUnderlyingError=0x7fe0b7c1e520 {Error Domain=NSPOSIXErrorDomain Code=2 "No such file or directory"}}}}
`

Any ideas on how to fix this?

**Comment by PolitieRool** [comment]
See https://github.com/SonarSource/sonar-scanning-examples/issues/63 for a possible solution

**Comment by guillermomartinez-accenture** [comment]
> I was trying to test the script with the above Xcode10 path after compiling the example code with the Xcode 11-beta
> `$DERIVED_DATA/Logs/Test/*.xcresult/*_Test/action.xccovarchive/`
> 
> Unfortunately, it returns an error like below
> `Error: Error Domain=XCCovErrorDomain Code=0 "Failed to create unarchiver" UserInfo={NSLocalizedDescription=Failed to create unarchiver, NSUnderlyingError=0x7fe0b7c1ecd0 {Error Domain=NSCocoaErrorDomain Code=260 "The file “Metadata.plist” couldn’t be opened because there is no such file." UserInfo={NSFilePath=/Users/username/Downloads/sonar-scanning-examples-master/swift-coverage/swift-coverage-example/Build/Logs/Test/*.xcresult/*_Test/*.xccovarchive/Metadata.plist, NSUnderlyingError=0x7fe0b7c1e520 {Error Domain=NSPOSIXErrorDomain Code=2 "No such file or directory"}}}} `
> 
> Any ideas on how to fix this?

I'm also facing the same error.
Error: Error Domain=XCCovErrorDomain Code=0 “Failed to create unarchiver” UserInfo={NSLocalizedDescription=Failed to create unarchiver, NSUnderlyingError=0x7fd861f05d80 {Error Domain=NSCocoaErrorDomain Code=260 “The file “Metadata.plist” couldn’t be opened because there is no such file.” UserInfo={NSFilePath=/Users/runner/runners/2.160.1/work/1/s/Build/Logs/Test/*.xcresult/_Test/.xccovarchive/Metadata.plist, NSUnderlyingError=0x7fd861f056b0 {Error Domain=NSPOSIXErrorDomain Code=2 “No such file or directory”}}}}

It has started appearing after updating to Xcode 11.2 and iOS 13.

**Comment by onurpolaatt** [comment]
Hi,
If you are using cocoapods in your projects, code coverage support will be provided with the '1.9.0' update.

**Comment by jaderYang** [comment]
Some people may be troubled by this problem. 
Today I found a simpler way than the official document to generate the coverage.xml file.
The latest version of slather supports directly generating xml files that support sonarqube format.
https://github.com/SlatherOrg/slather/pull/456.

**Comment by okorach** [comment]
Please follow-up on such problems on the SonarSource community (https://community.sonarsource.com), not on this sample repo.
Thanks
