### ISSUE TITLE
xccov-to-sonarqube-generic.sh doesn't handle & in filenames

### ISSUE THREAD

**Issue by jfbibeau** [SonarSource/sonar-scanning-examples#80]
I have a project with a source directory that has spaces and `&` in it. For example to reproduce, use a folder with the name `Drag & Drop`. 

`xccov-to-sonarqube-generic.sh` generates an XML that sonar-scanner seems to be unable to parse. It looks like the ampersand should be replaced with `&amp;` to be parsed properly by sonar-scanner (even though the initial error seems to imply the space is the problem).

```
ERROR: Error during parsing of the generic coverage report 'sonarqube-generic-coverage.xml'. Look at SonarQube documentation to know the expected XML format.
ERROR: Caused by: Unexpected character ' ' (code 32) (missing name?)
at [row,col {unknown-source}]: [21273,86]
```

**Comment by MarcoEidinger** [comment]
Same issue here! :(

**Comment by julianacipa** [comment]
I encountered the same issue. A folder had ` & ` in its name and this gave an error while parsing the generated xml report. The error is a little different than yours. I am posting it in here as it might help someone to debug:

`ERROR: Error during parsing of the generic coverage report 'sonarqube-generic-coverage.xml'. Look at SonarQube documentation to know the expected XML format.
ERROR: Caused by: Unexpected character '"' (code 34) (expected a name start character)
at [row,col {unknown-source}]: [187,16]
ERROR:
ERROR: Re-run SonarQube Scanner using the -X switch to enable full debug logging.`

Renaming the folder, by removing `&` from its name, resolved the issue.

**Comment by okorach** [comment]
This repo is a sample of how to scan basic projects.
If you have problems on your own projects please post on the SonarSource community forum, not here. See https://community.sonarsource.com
